apiVersion: 1

datasources:
  - name: Senior Pomidor PostgreSQL
    uid: senior-pomidor-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: senior_pomidor
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
